version: "3.9"

services:
  web:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 my_project.wsgi:application
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles

    ports:
      - "8000:8000"
